DECLARE @FATOR_MES INT = 6,
		@PRODUTO INT = 4750,
		@EMPRESA INT,
		@DTCALC DATE,
		@DTINI DATE,
		@DTFIM DATE;
		
SET @DTCALC = DATEADD(MONTH, (@FATOR_MES * -1), GETDATE())
SET @DTINI = DATEADD(DAY, 1, EOMONTH(@DTCALC, -2))
SET @DTFIM  = EOMONTH(GETDATE());

WITH TABELAS AS (
	SELECT 
		t.CODTAB,
		t.NUTAB,
		t.DTALTER,
		e.CODPROD,
		e.VLRVENDA
	FROM 
		TGFTAB t
		INNER JOIN TGFEXC e ON t.NUTAB = e.NUTAB
	WHERE 
		t.CODTAB = 0
		AND e.CODPROD =  @PRODUTO
		AND t.DTALTER BETWEEN @DTINI AND @DTFIM
)
SELECT 
	CODPROD,
	MIN(DTALTER) DATA_MINIMA_PERIODO,
	VLRVENDA
FROM 
	TABELAS
GROUP BY
	CODPROD,
	VLRVENDA